#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { bundleWeb } from "./build/scripts/build/bundle-web.js";

// get first and only command line argument
let src = process.argv[2];

// transform ts file name in the source tree to js file in /build
let srcjs = src.replace(/\.ts$/, ".js");
let entrypoint = path.resolve("build/", srcjs);

entrypoint = fs.existsSync(entrypoint) ? entrypoint : src;

let targetDir = path.dirname(path.join("build/web/", srcjs));
let absPath = await bundleWeb(entrypoint, targetDir);
let fileName = path.basename(absPath);
let filePath = path.join(targetDir, fileName);

console.log(`built fo the browser: ${filePath}`);
